### ISSUE TITLE
[FEATURE] Migration to NuxtJS

### ISSUE THREAD

**Issue by eng-gabrielscardoso** [eng-gabrielscardoso/eng-gabrielscardoso.github.io#54]
# Migration to NuxtJS

This PR is responsible to migrate the old ReactJS project to NuxtJS.

This migration should allows to move the old UI, features and infrastructure to a new approach.

## Tasks

- [x] #55
- [x] Install Pinia
- [x] Install Tailwind
- [x] Install i18n support
- [x] Install VueUse
- [x] Install Nuxt Images
- [x] Install Colour mode
- [x] Install Pinia plugin persisted state
- [x] Install ESLint + Prettier formatters
- [ ] Install Nuxt UI
- [ ] Install Google fonts module
- [ ] Install test-utils module
- [ ] Install Supabase
- [ ] Install Content module
- [ ] Install MDC module

## Future ideas

- [ ] Create a white-labeled architecture to allows other users to customise and setup they own portfolios using a config file like TOML, YAML or a JSON.
